using Piro.Domain.Enums;

namespace Piro.Domain.Entities;

/// <summary>A single materialized occurrence of a <see cref="Maintenance"/> window.</summary>
/// <remarks>
/// Generated by <c>MaintenanceSchedulerJob</c> from the parent's RRULE.
/// Status transitions: Scheduled → Ongoing → Completed (or Cancelled).
/// </remarks>
public class MaintenanceEvent
{
    public int Id { get; set; }
    public int MaintenanceId { get; set; }

    /// <summary>Unix timestamp (seconds) when this occurrence starts.</summary>
    public long StartDateTime { get; set; }

    /// <summary>Unix timestamp (seconds) when this occurrence ends.</summary>
    public long EndDateTime { get; set; }

    public MaintenanceEventStatus Status { get; set; } = MaintenanceEventStatus.Scheduled;

    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }

    public Maintenance Maintenance { get; set; } = null!;
}
