using Piro.Application.Models;

namespace Piro.Application.Interfaces;

/// <summary>
/// Accumulates results from all workers participating in a multi-region check execution
/// and triggers exactly one <see cref="ICheckResultIngester.IngestStatusOnlyAsync"/> call
/// once all expected results have arrived (or a safety timeout fires).
/// </summary>
public interface IMultiRegionBatchTracker
{
    /// <summary>
    /// Registers a new fan-out batch before dispatching to workers.
    /// Must be called once per multi-region execution cycle.
    /// </summary>
    /// <param name="batchId">Unique batch identifier generated by <c>RemoteCheckJobDispatcher</c>.</param>
    /// <param name="checkId">The check being executed.</param>
    /// <param name="expectedCount">Number of workers the check was dispatched to.</param>
    void RegisterBatch(string batchId, int checkId, int expectedCount);

    /// <summary>
    /// Records a single worker result. When the last expected result arrives the batch
    /// is completed synchronously; otherwise the call returns immediately.
    /// A safety timeout ensures completion even if one or more workers never respond.
    /// </summary>
    void AddResult(string batchId, CheckExecutionResult result);
}
